import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../theme/colors';

export const styles = StyleSheet.create({
  wrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 999,
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingBottom: Platform.OS === 'ios' ? 24 : 12,
  },
  discountBanner: {
    backgroundColor: '#E2F7C2',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    paddingVertical: 5,
    paddingHorizontal: 16,
    width: '92%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  discountText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1C3A27',
  },
  cartContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 14,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 10,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  leftSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 10,
  },
  restaurantImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  textContainer: {
    justifyContent: 'center',
    flex: 1,
  },
  cartCountText: {
    fontSize: 13.5,
    fontWeight: '700',
    color: COLORS.textDark,
  },
  fromRestaurantText: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  fromNameBold: {
    fontWeight: '700',
    color: COLORS.textDark,
  },
  rightSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkoutBtn: {
    backgroundColor: COLORS.bannerPink,
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.bannerPink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  checkoutBtnText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  closeBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  closeBtnText: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '700',
  },

  // Clear Cart Confirmation Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearModalCard: {
    width: '85%',
    backgroundColor: COLORS.white,
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 12,
  },
  clearModalTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: 8,
    textAlign: 'center',
  },
  clearModalSub: {
    fontSize: 14,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  modalBtnRow: {
    flexDirection: 'row',
    width: '100%',
    gap: 12,
  },
  cancelModalBtn: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  cancelModalBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#334155',
    letterSpacing: 0.3,
  },
  clearModalBtn: {
    flex: 1,
    backgroundColor: COLORS.bannerPink,
    borderRadius: 24,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.bannerPink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  clearModalBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.white,
    letterSpacing: 0.3,
  },
});
