import { StyleSheet } from 'react-native';
import { COLORS } from '../../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    backgroundColor: COLORS.white,
  },
  backBtn: {
    padding: 6,
    marginRight: 10,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textDark,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  locationCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FAF9F6',
    padding: 14,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  pinBox: {
    marginRight: 10,
    marginTop: 2,
  },
  locationCardTextContainer: {
    flex: 1,
  },
  locationAddressText: {
    fontSize: 14,
    fontFamily: 'OpenSans-Medium',
    color: COLORS.textDark,
    lineHeight: 20,
  },
  useLocationBtn: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  useLocationBtnText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.brandPink,
  },
  inputGroup: {
    marginBottom: 18,
  },
  inputLabel: {
    fontSize: 14,
    fontFamily: 'OpenSans-SemiBold',
    fontWeight: '600',
    color: COLORS.textDark,
    marginBottom: 8,
  },
  textInput: {
    fontSize: 14,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textDark,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.inputBorder,
    paddingVertical: 10,
    paddingHorizontal: 0,
  },
  sectionTitle: {
    fontSize: 15,
    fontFamily: 'OpenSans-SemiBold',
    fontWeight: '600',
    color: COLORS.textSub,
    marginTop: 10,
    marginBottom: 12,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  instructionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D4D4D8',
    backgroundColor: COLORS.white,
    marginRight: 10,
    marginBottom: 10,
  },
  chipSelected: {
    borderColor: COLORS.brandPink,
    backgroundColor: '#FFF0F5',
  },
  chipText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Medium',
    color: COLORS.textDark,
    marginLeft: 6,
  },
  chipTextSelected: {
    color: COLORS.brandPink,
    fontWeight: '600',
  },
  saveAsChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D4D4D8',
    backgroundColor: COLORS.white,
    marginRight: 12,
  },
  bottomContainer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  saveBtn: {
    backgroundColor: COLORS.bannerPink,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.bannerPink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  saveBtnText: {
    fontSize: 16,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.white,
  },
});
