import { StyleSheet, Platform, StatusBar } from 'react-native';
import { COLORS } from '../../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.screenBgLight,
  },
  heroContainer: {
    width: '100%',
    height: 230,
    position: 'relative',
    backgroundColor: COLORS.headerBlue,
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  topButtonsRow: {
    position: 'absolute',
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 50,
  },
  backBtnCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.overlayWhite,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
  },
  topRightRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchPillBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 38,
    paddingHorizontal: 12,
    borderRadius: 19,
    backgroundColor: COLORS.overlayWhite,
    marginRight: 8,
    elevation: 4,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
  },
  searchPlaceholderText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textSlateDark,
    marginLeft: 6,
  },
  shareBtnCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: COLORS.overlayWhite,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
  },
  restaurantInfoCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 16,
    marginTop: -44,
    borderRadius: 26,
    padding: 16,
    elevation: 4,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    zIndex: 30,
  },
  infoTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  cardHeaderLeft: {
    flex: 1,
    marginRight: 10,
  },
  restaurantTitle: {
    fontSize: 19,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textSlateDark,
    letterSpacing: 0.2,
    lineHeight: 24,
  },
  ratingBox: {
    alignItems: 'flex-end',
  },
  ratingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.badgeGreenSoftBg,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.badgeGreenSoftBorder,
  },
  ratingScoreText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.badgeGreen,
    marginLeft: 3,
  },
  ratingCountSub: {
    fontSize: 11,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textSlateMuted,
    marginTop: 2,
  },
  timeLocRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  timeLocText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textSlateIcon,
  },
  subLocText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textSlateMuted,
    marginTop: 2,
  },
  cardDividerLine: {
    height: 1,
    backgroundColor: COLORS.dividerLight,
    marginVertical: 10,
  },
  lowestPriceTagPill: {
    backgroundColor: COLORS.badgeGreenBg,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  badgeIconCircle: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: COLORS.badgeGreen,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  badgePercentSymbol: {
    fontSize: 9.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '900',
    color: COLORS.white,
    includeFontPadding: false,
    textAlign: 'center',
    lineHeight: 11,
  },
  badgeText: {
    fontSize: 11,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.badgeGreenText,
  },

  filterSection: {
    paddingVertical: 12,
    paddingHorizontal: 0,
    backgroundColor: COLORS.screenBgLight,
  },
  filterScroll: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 24,
  },
  filterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.borderFilter,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 13,
    marginRight: 8,
  },
  filterPillActive: {
    borderColor: COLORS.brandPink,
    backgroundColor: COLORS.filterPillActiveBg,
  },
  filterPillText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textSlateSub,
  },
  filterPillTextActive: {
    color: COLORS.brandPink,
  },

  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 16,
    paddingHorizontal: 20,
  },
  dividerLine: {
    height: 1,
    flex: 1,
    backgroundColor: COLORS.borderFilter,
  },
  sectionHeaderTitleText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textSlateMuted,
    letterSpacing: 1.5,
    marginHorizontal: 12,
  },

  /* TOP PICKS Card Styles Matching Reference Design */
  topPicksGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 12,
  },
  topPickCardOuter: {
    width: '47.5%',
    marginHorizontal: '1.25%',
    marginBottom: 16,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 5,
  },
  topPickCardInner: {
    borderRadius: 20,
    overflow: 'hidden',
    position: 'relative',
    height: 280,
  },
  topPickImageContainer: {
    width: '100%',
    height: 280,
    position: 'relative',
    backgroundColor: COLORS.cardBorderLight,
  },
  topPickImage: {
    width: '100%',
    height: '100%',
  },
  topPickGradientOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 145,
    backgroundColor: 'rgba(0,0,0,0.65)',
    paddingHorizontal: 10,
    paddingBottom: 10,
    justifyContent: 'flex-end',
  },
  vegBadgeOverlay: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  vegSquare: {
    width: 11,
    height: 11,
    borderWidth: 1,
    borderColor: COLORS.badgeGreen,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  vegDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: COLORS.badgeGreen,
  },
  topPickTitle: {
    fontSize: 15,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.white,
    marginBottom: 2,
  },
  topPickPrice: {
    fontSize: 15,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.white,
    marginBottom: 2,
  },
  topPickRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 1,
  },
  greenStarCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: COLORS.badgeGreen,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  topPickRatingText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Bold',
    color: COLORS.white,
    fontWeight: '700',
  },
  moreDetailsText: {
    fontSize: 11,
    fontFamily: 'OpenSans-Bold',
    color: 'rgba(255,255,255,0.9)',
    marginTop: 4,
  },
  addPlusCircleBtn: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.brandPink,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    zIndex: 10,
  },
  topPickQtyPill: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    height: 32,
    minWidth: 72,
    borderRadius: 16,
    backgroundColor: COLORS.brandPink,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    elevation: 4,
    zIndex: 10,
  },
  dishQtyPill: {
    position: 'absolute',
    bottom: -6,
    right: -6,
    height: 34,
    minWidth: 74,
    borderRadius: 17,
    backgroundColor: COLORS.brandPink,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    elevation: 6,
    zIndex: 10,
  },
  qtyPillBtnText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '900',
    paddingHorizontal: 4,
  },
  qtyPillNumText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '900',
    marginHorizontal: 4,
  },


  accordionSection: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  accordionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderFilter,
  },
  accordionTitleText: {
    fontSize: 18,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textSlateDark,
  },
  dishHorizontalRow: {
    flexDirection: 'row',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.cardBorderLight,
    alignItems: 'flex-start',
  },
  dishLeftCol: {
    flex: 1,
    paddingRight: 12,
  },
  dishNameText: {
    fontSize: 16,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textSlateDark,
    marginTop: 4,
  },
  dishPriceText: {
    fontSize: 15,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textSlateDark,
    marginTop: 4,
  },
  dishDescText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textSlateMuted,
    marginTop: 6,
    lineHeight: 16,
  },
  dishRightImageCol: {
    width: 110,
    height: 110,
    position: 'relative',
  },
  dishSquareImage: {
    width: 110,
    height: 110,
    borderRadius: 16,
    backgroundColor: COLORS.cardBorderLight,
  },
  dishPlusBtnFloating: {
    position: 'absolute',
    bottom: -6,
    right: -6,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: COLORS.brandPink,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },

  floatingMenuBtn: {
    position: 'absolute',
    right: 18,
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: COLORS.textSlateDark,
    borderWidth: 2,
    borderColor: COLORS.brandPink,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    zIndex: 150,
  },
  menuBtnText: {
    fontSize: 10.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.white,
    marginTop: 2,
  },

  modalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.modalBackdrop,
    zIndex: 300,
  },
  categorySheetCard: {
    position: 'absolute',
    right: 18,
    width: 220,
    backgroundColor: COLORS.textSlateDark,
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 18,
    elevation: 12,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    zIndex: 310,
  },
  categorySheetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
  },
  categorySheetText: {
    fontSize: 14,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.white,
  },
  categorySheetCount: {
    fontSize: 14,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.brandPink,
  },
  sortDropdownCard: {
    position: 'absolute',
    top: 310,
    left: 16,
    width: 200,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
    elevation: 8,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    zIndex: 210,
    borderWidth: 1,
    borderColor: COLORS.borderFilter,
  },
  sortOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: COLORS.radioUnselectedBorder,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  radioOuterSelected: {
    borderColor: COLORS.brandPink,
  },
  radioInnerDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.brandPink,
  },
  sortOptionText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '600',
    color: COLORS.textSlateSub,
  },
  sortOptionTextSelected: {
    color: COLORS.textSlateDark,
    fontWeight: '800',
  },
});
