import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '../../../theme/colors';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.screenBgLight,
  },
  scrollContent: {
    paddingBottom: 60,
  },
  locationSection: {
    backgroundColor: COLORS.headerBlue,
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 8,
    justifyContent: 'center',
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  locationLeft: {
    flex: 1,
  },
  locationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationTitle: {
    fontSize: 15,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.white,
    marginRight: 4,
  },
  locationSub: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 2,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  vegToggleRow: {
    alignItems: 'center',
    marginRight: 10,
  },
  vegLabel: {
    fontSize: 10,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.white,
    marginBottom: 2,
  },
  profileAvatarBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.white,
    overflow: 'hidden',
  },
  stickySearchSection: {
    backgroundColor: COLORS.headerBlue,
    paddingHorizontal: 16,
    paddingBottom: 14,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    zIndex: 100,
    elevation: 6,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.white,
    paddingHorizontal: 14,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textDark,
    marginLeft: 8,
    paddingVertical: 0,
  },
  bannerContainer: {
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: COLORS.headerBlueDark,
    height: 140,
    position: 'relative',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  bannerTitle: {
    fontSize: 18,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#FFD700',
    width: '65%',
  },
  bannerSub: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    color: COLORS.white,
    marginTop: 4,
  },
  playBtn: {
    marginTop: 10,
    backgroundColor: COLORS.brandPink,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 16,
    alignSelf: 'flex-start',
  },
  playBtnText: {
    color: COLORS.white,
    fontSize: 12,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 17,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textDark,
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 14,
  },
  bestsellerContainer: {
    backgroundColor: '#FFF8FA',
    borderRadius: 24,
    paddingVertical: 18,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginBottom: 20,
  },
  bestsellerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  bestsellerTitle: {
    fontSize: 18,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.brandPink,
  },
  seeAllText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.brandPink,
  },
  foodScroll: {
    paddingRight: 10,
  },
  foodCard: {
    width: 145,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 10,
    marginRight: 12,
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  foodImgBox: {
    width: '100%',
    height: 105,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  foodEmoji: {
    fontSize: 48,
  },
  addBtn: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.brandPink,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  vegDotRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  vegSquare: {
    width: 12,
    height: 12,
    borderWidth: 1,
    borderColor: COLORS.badgeGreen,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  vegDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.badgeGreen,
  },
  foodTitle: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textDark,
    marginBottom: 4,
    height: 36,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  priceTag: {
    backgroundColor: '#FFF0F5',
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 8,
    marginRight: 6,
  },
  priceText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.brandPink,
  },
  strikePrice: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textPlaceholder,
    textDecorationLine: 'line-through',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 6,
  },
  ratingText: {
    fontSize: 11,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.badgeGreen,
    marginLeft: 2,
  },
  timeText: {
    fontSize: 11,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textMuted,
  },
  verticalFoodList: {
    paddingHorizontal: 16,
  },
  restaurantCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 12,
    marginBottom: 14,
    alignItems: 'center',
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  restaurantImgBox: {
    width: 80,
    height: 80,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  restaurantInfo: {
    flex: 1,
  },
  restaurantName: {
    fontSize: 15,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textDark,
    marginBottom: 2,
  },
  restaurantCuisine: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textMuted,
    marginBottom: 6,
  },
});
