import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
  },
  filterSection: {
    backgroundColor: COLORS.screenBgLight,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    elevation: 3,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    zIndex: 90,
  },
  sectionHeaderTitle: {
    fontSize: 19,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textDark,
    marginBottom: 10,
  },
  filterScroll: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginRight: 8,
  },
  filterPillActive: {
    borderColor: COLORS.headerBlueDark,
    backgroundColor: '#EFF6FF',
  },
  filterPillText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#334155',
  },
  vegDotCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#16A34A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  vegDotInside: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#16A34A',
  },
  percentBadgeIcon: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#0F172A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  percentBadgeText: {
    fontSize: 9,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '900',
    color: COLORS.white,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
    marginBottom: 18,
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  imageBox: {
    width: '100%',
    height: 175,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F1F5F9',
    marginBottom: 10,
  },
  cardImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },
  badgeContainer: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: '#9EE438',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgeIconCircle: {
    width: 13,
    height: 13,
    borderRadius: 6.5,
    backgroundColor: '#1C3A27',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  badgePercentSymbol: {
    fontSize: 8.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '900',
    color: '#9EE438',
    lineHeight: 11,
    textAlign: 'center',
  },
  badgeText: {
    fontSize: 10.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: '#0F172A',
  },
  infoContainer: {
    paddingHorizontal: 2,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  restaurantName: {
    fontSize: 16.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: '#0F172A',
    flex: 1,
    marginRight: 8,
  },
  locationRight: {
    alignItems: 'flex-end',
  },
  distanceText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#64748B',
  },
  locationText: {
    fontSize: 11,
    fontFamily: 'OpenSans-Regular',
    color: '#94A3B8',
    marginTop: 1,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#16A34A',
    marginLeft: 3,
  },
  ratingCountText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Regular',
    color: '#64748B',
    marginLeft: 2,
  },
  bulletDot: {
    fontSize: 13,
    color: '#64748B',
    marginHorizontal: 4,
  },
  timeText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Regular',
    color: '#475569',
  },
  priceCuisineRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  priceText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Regular',
    color: '#64748B',
  },
  cuisineText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Regular',
    color: '#64748B',
  },
});
