import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
  },
  filterSection: {
    backgroundColor: COLORS.screenBgLight,
    paddingVertical: 10,
    paddingHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderFilter,
    elevation: 3,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    zIndex: 90,
  },
  sectionHeaderTitle: {
    fontSize: 19,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textDark,
    marginHorizontal: 16,
    marginBottom: 10,
  },
  filterScroll: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 24,
  },
  filterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.borderFilter,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginRight: 8,
  },
  filterPillActive: {
    borderColor: COLORS.brandPink,
    backgroundColor: COLORS.filterPillActiveBg,
  },
  filterPillText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textSlateSub,
  },
  filterPillTextActive: {
    color: COLORS.brandPink,
  },
  vegDotCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: COLORS.badgeGreen,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  vegDotInside: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.badgeGreen,
  },
  percentBadgeIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.brandPink,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  percentBadgeText: {
    fontSize: 10,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '900',
    color: COLORS.white,
    includeFontPadding: false,
    textAlign: 'center',
    lineHeight: 12,
  },

  /* Vertical Card Layout (Home Screen All Restaurants) */
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: COLORS.cardBorderLight,
    padding: 12,
    marginBottom: 18,
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  imageBox: {
    width: '100%',
    height: 175,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: COLORS.cardBorderLight,
    marginBottom: 10,
  },
  cardImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },
  badgeContainer: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: COLORS.badgeGreenBg,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgeIconCircle: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: COLORS.badgeGreen,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  badgePercentSymbol: {
    fontSize: 9.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '900',
    color: COLORS.white,
    includeFontPadding: false,
    textAlign: 'center',
    lineHeight: 11,
  },
  badgeText: {
    fontSize: 10.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.badgeGreenText,
  },
  infoContainer: {
    paddingHorizontal: 2,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  restaurantName: {
    fontSize: 16.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textSlateDark,
    flex: 1,
    marginRight: 8,
  },
  distanceCol: {
    alignItems: 'flex-end',
  },
  distanceText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textSlateMuted,
  },
  locationText: {
    fontSize: 11,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textSlateLight,
    marginTop: 1,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.badgeGreen,
    marginLeft: 3,
  },
  ratingCountText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textSlateMuted,
    marginLeft: 2,
  },
  bulletDot: {
    fontSize: 12,
    color: COLORS.textSlateMuted,
    marginHorizontal: 4,
  },
  timeText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textSlateIcon,
  },
  priceCuisineRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  priceCuisineText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textSlateMuted,
  },
});
