import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.breakfastSoftBg,
    borderRadius: 28,
    paddingVertical: 20,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.breakfastSoftBorder,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  titleContainer: {
    flexDirection: 'column',
  },
  titlePinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  titlePink: {
    fontSize: 22,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.brandPink,
    lineHeight: 26,
  },
  titleYellow: {
    fontSize: 20,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.knownLovedOrange,
    marginLeft: 6,
    lineHeight: 26,
  },
  seeAllPill: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 16,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  seeAllText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.brandPink,
  },
  foodScroll: {
    paddingRight: 8,
  },
  foodCard: {
    width: 140,
    marginRight: 14,
    backgroundColor: COLORS.transparent,
  },
  foodImgBox: {
    width: 140,
    height: 140,
    borderRadius: 20,
    backgroundColor: COLORS.dividerLight,
    position: 'relative',
    overflow: 'hidden',
    marginBottom: 10,
  },
  foodImage: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  addBtn: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.bannerPink,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: COLORS.bannerPink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
  },
  qtyPillBox: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    height: 30,
    minWidth: 68,
    borderRadius: 15,
    backgroundColor: COLORS.bannerPink,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    elevation: 4,
    shadowColor: COLORS.bannerPink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
  },
  qtyBtnPillText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '900',
    paddingHorizontal: 4,
  },
  qtyTextPill: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '900',
    marginHorizontal: 4,
  },


  vegTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  vegSquare: {
    width: 13,
    height: 13,
    borderWidth: 1,
    borderColor: COLORS.badgeGreen,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
    marginTop: 2,
  },
  vegDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.badgeGreen,
  },
  nonVegSquare: {
    width: 13,
    height: 13,
    borderWidth: 1,
    borderColor: COLORS.error,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
    marginTop: 2,
  },
  nonVegDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.error,
  },
  foodTitle: {
    flex: 1,
    fontSize: 13.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textDark,
    lineHeight: 18,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  priceTag: {
    backgroundColor: COLORS.cravingBg,
    borderColor: COLORS.brandPinkLight,
    borderWidth: 1,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 10,
    marginRight: 6,
  },
  priceText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.brandPink,
  },
  strikePrice: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textPlaceholder,
    textDecorationLine: 'line-through',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
  },
  ratingText: {
    fontSize: 11.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.badgeGreen,
    marginLeft: 3,
  },
  timeText: {
    fontSize: 11.5,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textMuted,
  },
  restaurantName: {
    fontSize: 11.5,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textMuted,
  },
});
