import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#FFF8F6',
    borderRadius: 28,
    paddingVertical: 20,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#FFEFEA',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  titleContainer: {
    flexDirection: 'column',
  },
  titlePinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  titlePink: {
    fontSize: 22,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#FF1E6A',
    lineHeight: 26,
  },
  titleYellow: {
    fontSize: 20,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#FF9500',
    marginLeft: 6,
    lineHeight: 26,
  },
  seeAllPill: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 16,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  seeAllText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#FF1E6A',
  },
  foodScroll: {
    paddingRight: 8,
  },
  foodCard: {
    width: 140,
    marginRight: 14,
    backgroundColor: 'transparent',
  },
  foodImgBox: {
    width: 140,
    height: 140,
    borderRadius: 20,
    backgroundColor: '#F1F5F9',
    position: 'relative',
    overflow: 'hidden',
    marginBottom: 10,
  },
  foodImage: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  addBtn: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FF2A75',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#FF2A75',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
  },
  vegTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  vegSquare: {
    width: 13,
    height: 13,
    borderWidth: 1,
    borderColor: '#16A34A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
    marginTop: 2,
  },
  vegDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#16A34A',
  },
  foodTitle: {
    flex: 1,
    fontSize: 13.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#18181B',
    lineHeight: 18,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  priceTag: {
    backgroundColor: '#FFF0F5',
    borderColor: '#FFD6E5',
    borderWidth: 1,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 10,
    marginRight: 6,
  },
  priceText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#FF1E6A',
  },
  strikePrice: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: '#A1A1AA',
    textDecorationLine: 'line-through',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
  },
  ratingText: {
    fontSize: 11.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#16A34A',
    marginLeft: 3,
  },
  timeText: {
    fontSize: 11.5,
    fontFamily: 'OpenSans-Regular',
    color: '#71717A',
  },
  restaurantName: {
    fontSize: 11.5,
    fontFamily: 'OpenSans-Regular',
    color: '#8E8E93',
  },
});
