import { StyleSheet } from 'react-native';
import { COLORS } from '../../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.screenBgLight,
  },
  headerBanner: {
    width: '100%',
    paddingHorizontal: 20,
    paddingBottom: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
    position: 'relative',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    elevation: 2,
  },
  bannerContentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bannerTextCol: {
    flex: 1,
    paddingRight: 12,
  },
  crownBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  crownEmoji: {
    fontSize: 18,
    marginRight: 4,
  },
  bannerTitle: {
    fontSize: 32,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '900',
    color: COLORS.white,
    lineHeight: 38,
    letterSpacing: -0.5,
  },
  // Bestseller specific header typography
  bestsellerTitle: {
    fontSize: 34,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '900',
    color: '#FDE047',
    letterSpacing: -0.5,
  },
  bestsellerUnder: {
    fontSize: 22,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.white,
    marginTop: -4,
  },
  bestsellerPrice: {
    fontSize: 48,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '900',
    color: COLORS.white,
    lineHeight: 52,
    letterSpacing: -1,
  },
  subtitlePillYellow: {
    backgroundColor: COLORS.yellowBadgeBg,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 14,
    alignSelf: 'flex-start',
    marginTop: 10,
  },
  subtitlePillYellowText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.badgeGreenDark,
  },
  subtitleTextWhite: {
    fontSize: 13,
    fontFamily: 'OpenSans-Regular',
    color: 'rgba(255, 255, 255, 0.92)',
    marginTop: 6,
  },
  bannerRightImageBox: {
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bannerRightImage: {
    width: '100%',
    height: '100%',
  },

  // Category Tabs Bar
  tabBarContainer: {
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingVertical: 4,
  },
  tabScroll: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  tabItem: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    position: 'relative',
  },
  tabItemActive: {
    borderBottomWidth: 3,
    borderBottomColor: COLORS.bannerPink,
  },
  tabText: {
    fontSize: 14,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: '#64748B',
  },
  tabTextActive: {
    color: COLORS.bannerPink,
    fontWeight: '800',
  },

  filterBarContainer: {
    backgroundColor: COLORS.screenBgLight,
    paddingVertical: 12,
    paddingHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderFilter,
  },
  filterScroll: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 24,
  },
  filterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.borderFilter,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 13,
    marginRight: 8,
  },
  filterPillActive: {
    borderColor: COLORS.brandPink,
    backgroundColor: COLORS.filterPillActiveBg,
  },
  filterPillText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textSlateSub,
  },
  filterPillTextActive: {
    color: COLORS.brandPink,
  },
  vegDotCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: COLORS.badgeGreen,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  vegDotInside: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.badgeGreen,
  },
  percentBadgeIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.brandPink,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  percentBadgeText: {
    fontSize: 10,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '900',
    color: COLORS.white,
    includeFontPadding: false,
    textAlign: 'center',
    lineHeight: 12,
  },

  // Food List Container & Cards
  foodListContainer: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 40,
  },
  foodCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    padding: 16,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  foodLeftCol: {
    flex: 1,
    paddingRight: 14,
  },
  vegSquare: {
    width: 14,
    height: 14,
    borderWidth: 1.5,
    borderColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 3,
    marginBottom: 4,
  },
  vegDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#16A34A',
  },
  nonVegSquare: {
    width: 14,
    height: 14,
    borderWidth: 1.5,
    borderColor: '#DC2626',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 3,
    marginBottom: 4,
  },
  nonVegDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#DC2626',
  },
  foodName: {
    fontSize: 16,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textDark,
    marginTop: 2,
    letterSpacing: -0.2,
  },
  foodPrice: {
    fontSize: 16,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textDark,
    marginTop: 4,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  ratingBadgeGreen: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingGreenText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: '#16A34A',
    marginLeft: 3,
  },
  ratingCountText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: '#64748B',
    marginLeft: 2,
  },
  bulletDot: {
    fontSize: 12,
    color: '#94A3B8',
    marginHorizontal: 4,
  },
  timeText: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-SemiBold',
    fontWeight: '600',
    color: '#475569',
    marginLeft: 3,
  },
  restaurantSub: {
    fontSize: 12.5,
    fontFamily: 'OpenSans-Regular',
    color: '#64748B',
    marginTop: 4,
  },

  // Food Right Image & Plus Button
  foodRightCol: {
    width: 104,
    height: 104,
    position: 'relative',
  },
  foodImageBox: {
    width: 104,
    height: 104,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#F3F4F6',
  },
  foodCardImage: {
    width: '100%',
    height: '100%',
  },
  plusBtnCircle: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: COLORS.bannerPink,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.bannerPink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 5,
  },
  qtyPillOverlay: {
    position: 'absolute',
    right: -6,
    bottom: -4,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bannerPink,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 5,
    shadowColor: COLORS.bannerPink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 5,
  },
  qtyBtnText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '900',
    paddingHorizontal: 4,
  },
  qtyText: {
    color: COLORS.white,
    fontSize: 13.5,
    fontWeight: '900',
    marginHorizontal: 4,
  },

  // Restaurant List Section
  restaurantListContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
  },
  horizontalCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.cardBorderLight,
    padding: 12,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
  },
  horizontalImageBox: {
    width: 108,
    height: 108,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: COLORS.cardBorderLight,
  },
  horizontalCardImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },
  badgeContainer: {
    backgroundColor: COLORS.badgeGreenBg,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginBottom: 4,
  },
  badgeIconCircle: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: COLORS.badgeGreen,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  badgePercentSymbol: {
    fontSize: 9.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '900',
    color: COLORS.white,
    includeFontPadding: false,
    textAlign: 'center',
    lineHeight: 11,
  },
  badgeText: {
    fontSize: 10.5,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.badgeGreenText,
  },
  infoContainer: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
  },
  restaurantName: {
    fontSize: 16,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '800',
    color: COLORS.textSlateDark,
    marginBottom: 3,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.badgeGreen,
    marginLeft: 3,
  },
  locationText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textSlateMuted,
    marginTop: 1,
  },
  cuisineText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textSlateMuted,
    marginTop: 2,
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.modalBackdrop,
    zIndex: 200,
  },
  sortDropdownCard: {
    position: 'absolute',
    top: 245,
    left: 16,
    width: 220,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
    elevation: 8,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    zIndex: 210,
    borderWidth: 1,
    borderColor: COLORS.borderFilter,
  },
  sortOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: COLORS.radioUnselectedBorder,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  radioOuterSelected: {
    borderColor: COLORS.brandPink,
  },
  radioInnerDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.brandPink,
  },
  sortOptionText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '600',
    color: COLORS.textSlateSub,
  },
  sortOptionTextSelected: {
    color: COLORS.textSlateDark,
    fontWeight: '800',
  },
  emptyContainer: {
    padding: 30,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    fontFamily: 'OpenSans-Bold',
    color: COLORS.textSlateMuted,
  },
});
