import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '../../../theme/colors';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.screenBgLight,
  },
  headerBanner: {
    backgroundColor: COLORS.profileHeaderPink,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  topNavRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  editBtn: {
    backgroundColor: COLORS.white,
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 16,
  },
  editText: {
    fontSize: 13,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.splashBg,
  },
  userInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  userName: {
    fontSize: 20,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.white,
  },
  userPhone: {
    fontSize: 13,
    fontFamily: 'OpenSans-Regular',
    color: 'rgba(255, 255, 255, 0.9)',
    marginTop: 2,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 40,
  },
  menuCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginBottom: 16,
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
  },
  menuItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  iconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  menuTextContainer: {
    flex: 1,
  },
  menuTitle: {
    fontSize: 15,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textDark,
  },
  menuSubtitle: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textMuted,
    marginTop: 2,
  },
  feedbackCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 16,
    marginBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  feedbackLeft: {
    flex: 1,
  },
  feedbackTitle: {
    fontSize: 15,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.textDark,
    marginBottom: 4,
  },
  feedbackSub: {
    fontSize: 12,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.brandPink,
  },
  starGraphics: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DCFCE7',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 16,
  },
  starText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.badgeGreen,
    marginLeft: 4,
  },
  logoutBtn: {
    alignItems: 'center',
    paddingVertical: 12,
    marginBottom: 20,
  },
  logoutText: {
    fontSize: 16,
    fontFamily: 'OpenSans-Bold',
    fontWeight: '700',
    color: COLORS.error,
  },
  copyrightText: {
    fontSize: 11,
    fontFamily: 'OpenSans-Regular',
    color: COLORS.textMuted,
    textAlign: 'center',
    lineHeight: 18,
  },
});
